//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SupportLayer.DatabaseModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.OrderLocations = new HashSet<OrderLocation>();
        }
    
        public short ID { get; set; }
        public short ClientId { get; set; }
        public byte ProductId { get; set; }
        public int AmountofWishedSeedlings { get; set; }
        public int AmountofAlgorithmSeedlings { get; set; }
        public System.DateTime WishDate { get; set; }
        public System.DateTime DateOfRequest { get; set; }
        public System.DateTime EstimateSowDate { get; set; }
        public System.DateTime EstimateDeliveryDate { get; set; }
        public Nullable<System.DateTime> RealSowDate { get; set; }
        public Nullable<System.DateTime> RealDeliveryDate { get; set; }
        public bool Complete { get; set; }
    
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLocation> OrderLocations { get; set; }
        public virtual Product Product { get; set; }
    }
}
