//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Greenhouse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Greenhouse()
        {
            this.OrderLocations = new HashSet<OrderLocation>();
        }
    
        public byte GreenHouseID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Width { get; set; }
        public Nullable<decimal> Lenght { get; set; }
        public Nullable<decimal> GreenHouseArea { get; set; }
        public decimal SeedTrayArea { get; set; }
        public byte AmountOfBlocks { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLocation> OrderLocations { get; set; }
    }
}
