//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderLocation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderLocation()
        {
            this.Blocks = new HashSet<Block>();
        }
    
        public int OrderLocationID { get; set; }
        public byte IdGreenHouse { get; set; }
        public byte IdSeedTray { get; set; }
        public short IdOrder { get; set; }
        public short SeedTrayAmount { get; set; }
        public int SeedlingAmount { get; set; }
        public Nullable<System.DateTime> SowDate { get; set; }
        public Nullable<System.DateTime> EstimateDeliveryDate { get; set; }
        public Nullable<System.DateTime> RealDeliveryDate { get; set; }
        public Nullable<bool> Sown { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Block> Blocks { get; set; }
        public virtual Greenhouse Greenhouse { get; set; }
        public virtual Order Order { get; set; }
        public virtual SeedTray SeedTray { get; set; }
    }
}
