//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SeedTray
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SeedTray()
        {
            this.OrderLocations = new HashSet<OrderLocation>();
        }
    
        public byte SeedTrayID { get; set; }
        public string Name { get; set; }
        public short TotalAlveolus { get; set; }
        public Nullable<byte> AlveolusLength { get; set; }
        public Nullable<byte> AlveolusWidth { get; set; }
        public Nullable<decimal> TrayLength { get; set; }
        public Nullable<decimal> TrayWidth { get; set; }
        public decimal TrayArea { get; set; }
        public short TotalAmount { get; set; }
        public string Material { get; set; }
        public byte Preference { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderLocation> OrderLocations { get; set; }
    }
}
